### ISSUE TITLE
MatchParen difficult to see

### ISSUE THREAD

**Issue by unknowledgeable** [skbolton/embark#6]
I've had to add this to my vimrc:

```
hi MatchParen guibg='#F8F8F2' guifg='#1E1C31'
```
Couldn't remember the names of these colours so used Hex values I saved from your reddit post. Might be nice to add a chart of colors and their names (+terminal colors) to your readme and/or a mention of `:so $VIMRUNTIME/syntax/hitest.vim` and similar.

**Comment by skbolton** [comment]
Yeah I need to add some more details around the palette choice to the readme. I am also planning on pulling this scheme into an organization so that I can add all the other ports. Similar to what the nord colorscheme does.

As far as your change above it seems you are changing a color and then flipping the bg and fg? Right now the match paren bg is the same as the editor and the fg is purple. Above it looks like you are making the background yellow and the text the background color?

**Comment by unknowledgeable** [comment]
Just realised this may be a result of using [rainbow_parentheses](https://github.com/junegunn/rainbow_parentheses.vim) and that causing me the trouble! The colours would have been easier to distinguish if they weren't all different. Apologies for hassling you unnecessarily.

Organization sounds cool though!
